### ISSUE TITLE
"View more" link for Support section on product pages reloads page at the top

### ISSUE THREAD

**Issue by partydrone** [wavetronix/glados#192]

**Comment by partydrone** [comment]
My suggestion: Get rid of it—it's not doing anything.

**Comment by conterio** [comment]
@partydrone  thanks

**Comment by ZRichins** [comment]
Why isn't this working properly? This should be showing only the first row of support documents and then hiding the rest until the user chooses to view more.

**Comment by partydrone** [comment]
@ZRichins, @ehuntsman never implemented this behavior. Part of the reason why is because of how you wanted each section to flow together like Pinterest. And since we just barely decided to change that, it's easier to simply remove the link.

There's really no impact—not hiding those download links doesn't prevent a visitor from getting to any more content on the page. Do you think adding the "view more" behavior is worth delaying the launch?

**Comment by ZRichins** [comment]
No I wouldn’t delay launch for this. I do, however, think it would improve the UX and should be implemented later.


On May 25, 2017, at 2:08 PM, Andrew Porter <notifications@github.com<mailto:notifications@github.com>> wrote:


@ZRichins<https://github.com/zrichins>, @ehuntsman<https://github.com/ehuntsman> never implemented this behavior. Part of the reason why is because of how you wanted each section to flow together like Pinterest. And since we just barely decided to change that, it's easier to simply remove the link.

There's really no impact—not hiding those download links doesn't prevent a visitor from getting to any more content on the page. Do you think adding the "view more" behavior is worth delaying the launch?
