### ISSUE TITLE
Blog post bug

### ISSUE THREAD

**Issue by ZRichins** [wavetronix/glados#264]
## Expected Behavior
Text stay in the column.

## Actual Behavior
Currently it’s running behind the ‘related articles’ section in the first paragraph.

## Steps to Reproduce the Problem

1. Open the recently published Rob Klug story
![img_0056](https://user-images.githubusercontent.com/11444985/28801410-a2fcd4aa-760e-11e7-805d-14b5f6f807cf.PNG)

## Specifications

- Operating system: iOS
- Browser: Safari

**Comment by partydrone** [comment]
So, it turns out this is a content issue. I checked the underlying code and noticed there were a whole bunch of random &nbsp; (non-breaking space) entities littered throughout the text. There really isn't much I can do to fix it on the backend; it will need to be addressed with the content creators.

For that article, I copied the text from the form, pasted it into a text editor, then copied the text from the text editor and pasted it back into the form, then saved the article. This effectively removed all the non-breaking spaces.

It looks like Jen posted that article. I will check with her to see how the article was authored to try and narrow down the source of the problem.
